version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: creative-backend
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: creative-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
